# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee24bca70e1ca4cc771dde515632e6e3032822c0e21894fcf08da9a19aa79b1d1de93b05f1da48dcec7f05513649d6b89c13c7e244f9c00921b8fbe3856ccfe0

test:
  secret_key_base: 09cb89ee7d3dac72adf9306121b4e03a69380d5144e352b975c4a1dde4bce28359116e3f83dc2632e3884eff945da28d5b714845673710185dda02e2c8012e06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
